
			<ol>
				<li><?php echo _("<strong>All fields are optional.</strong> You can search by given name, by surname, or a combination of both.  You can also limit your search results to a specific geographic area.  And you can choose to sort your results by different criteria, if you like."); ?></li>
                <li><?php echo _("<strong>Expand and contract your records.</strong>  Click on the blue plus sign next to each of your search results to show all of the information about a given record, not just the primary names associated with it."); ?></li>
                <li><?php echo _("<strong>Use facets to narrow your search results.</strong>  You can click on the links in the sidebar to focus your search on a particular \"facet\", or sub-set of your search results, such as record type, town, year, etc.  The facets will also help give you an overview of all information associated with your search, such as the other surnames commonly attached to the surname you queried, the towns often associated with the surname, etc."); ?></li>
                <li><?php echo _("<strong>You can use asterisks to do wildcard searches.</strong> For example, entering <span class=\"search-example\">SCHR*</span> in the surname field will show all surnames beginning with that string, such as SCHRANK, SCHREYER, etc.  You can also use a wildcard (or even <strong>multiple wildcards!</strong>) in the middle or the end of a name, such as <span class=\"search-example\">*WITZ</span> or <span class=\"search-example\">K*H*N</span>.  There is no minimum number of letters that you have to enter.  Wildcards will work in the Given Name field too."); ?></li>
                <li><?php echo _("<strong>Some common synonyms and kinnui for Given Names have been enabled.</strong>  For example, searching for <span class=\"search-example\">Rebecca</span> will also turn up matches for names like Rivka, Becky, etc.  A search for <span class=\"search-example\">Hersch</span> will find spelling variants like Hers and Hirsch, but also Tvi and Zvi. <a href=\"http://www.jewishgen.org/InfoFiles/GivenNames/\">Learn more about Jewish given names and kinnui here.</a>"); ?></li>
                <li><?php echo _("<strong>Map that town!</strong> If your record results show a modern-day town name underlined in light blue, click that link to show a helpful pop-up map of the area."); ?></li>
                <li><?php echo _("<strong>Soundalike / Soundex / Phonetic searching is not enabled yet.</strong>  <a href=\"http://stevemorse.org/phonetics/bmpm.htm\">Beider-Morse Phonetic Matching (BMPM)</a> is coming soon!  In the meantime, please use wildcards to look for variant spellings (or misspellings) of your names."); ?></li>
			</ol>
